---
version: '3'

services:
  swagger-editor:
    # https://hub.docker.com/r/swaggerapi/swagger-editor/
    image: swaggerapi/swagger-editor:${SWAGGER_EDITOR_VERSION:-latest}
    container_name: swagger_editor
    environment:
      - SWAGGER_FILE=${SWAGGER_FILE:-/tmp/swagger.json}
    volumes:
      - ${SWAGGER_EDITOR_PATH:-~/Projects/REST_API_Server/swagger}:/tmp
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
